spring:
  profile:
    active: local
  application:
    name: SeasonfreeClient
  devtools:
    remote:
      restart:
        enabled: true
      livereload:
        enabled: true
  jackson:
    time-zone: Asia/Seoul

  servlet:
    multipart:
      enabled: true
      max-request-size: 5MB
      max-file-size: 5MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

  profiles:
    include: oauth

logging:
  level:
    org.springframework.security: debug
    org.hibernate.SQL: debug

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: health, info, beans, conditions
        exclude: threaddump, heapdump

info:
  contact:
    email: hyeongju1122@gmail.com

jwt:
  secret: ${jwt.secret}
---
server:
  port: 8080

spring:
  config:
    active:
      on-profile: local

  data:
    redis:
      port: 6379
      host: localhost
      password: localhost

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      dialect: MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/seasonfree?charsetEncoding=UTF-8
    username: ${mariadb.username}
    password: ${mariadb.password}
---
server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  config:
    activate:
      on-profile: docker-local

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: ${redis.password}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # 이부분 반드시 바꿔야 한다.(staging, production, local)
      dialect: MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://mariadb-container:3306/seasonfree?charsetEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${mariadb.username}
    password: ${mariadb.password}
---
server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true

spring:
  config:
    activate:
      on-profile: staging

  data:
    redis:
      port: 6379
      host: 127.0.0.1
      password: ${redis.password}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
      dialect: MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://database-1.che2y8wum9oi.ap-northeast-2.rds.amazonaws.com:3306/seasonfree?charsetEncoding=UTF-8&useUnicode=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${mariadb.username}
    password: ${mariadb.password}
---
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: production

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: validate
      dialect: MariaDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mariadb://rds-address-production:3306/seasonfree?charsetEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${mariadb.username}
    password: ${mariadb.password}